// Code generated by ogen, DO NOT EDIT.
package api

type SubscriptionCalculateTotalCostPostRes interface {
	subscriptionCalculateTotalCostPostRes()
}

type SubscriptionGetRes interface {
	subscriptionGetRes()
}

type SubscriptionIDDeleteRes interface {
	subscriptionIDDeleteRes()
}

type SubscriptionIDGetRes interface {
	subscriptionIDGetRes()
}

type SubscriptionIDPatchRes interface {
	subscriptionIDPatchRes()
}

type SubscriptionPostRes interface {
	subscriptionPostRes()
}
