// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	SubscriptionCalculateTotalCostPostOperation OperationName = "SubscriptionCalculateTotalCostPost"
	SubscriptionGetOperation                    OperationName = "SubscriptionGet"
	SubscriptionIDDeleteOperation               OperationName = "SubscriptionIDDelete"
	SubscriptionIDGetOperation                  OperationName = "SubscriptionIDGet"
	SubscriptionIDPatchOperation                OperationName = "SubscriptionIDPatch"
	SubscriptionPostOperation                   OperationName = "SubscriptionPost"
)
